version: '3.1'
services:
  springbootapp:
    image: 65.0.6.89:8084/spring_mongoapp:21
    ports:
    - 8080:8080
    restart: always
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@1234
    networks:
    - spring_mongonetwork
    depends_on:
    - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@1234
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
    - spring_mongonetwork
    volumes:
    - mongovolume:/data/db
volumes:
  mongovolume:
          #driver: rexray/ebs
    # external: true
networks:
  spring_mongonetwork:
    driver: overlay        
          #external: true
